// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LLTK1ec73N2Dl9StBOt7sGecde_b6-A',
    appId: '1:115438294651:web:130edcebcae3db464974de',
    messagingSenderId: '115438294651',
    projectId: 'flutter-individual',
    authDomain: 'flutter-individual.firebaseapp.com',
    storageBucket: 'flutter-individual.appspot.com',
    measurementId: 'G-YZWL33YW1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDQv3GxNe5SmkW3TdVfpQknMokKxVkQY',
    appId: '1:115438294651:android:8fa1461ef71e88fc4974de',
    messagingSenderId: '115438294651',
    projectId: 'flutter-individual',
    storageBucket: 'flutter-individual.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7SPJv9Q43vfIkLu16FtwsW0ww5_sASC8',
    appId: '1:115438294651:ios:3641fcb6bd151d994974de',
    messagingSenderId: '115438294651',
    projectId: 'flutter-individual',
    storageBucket: 'flutter-individual.appspot.com',
    iosClientId: '115438294651-l42613c6s9fc4mk2dcq83tfdrhcmkrfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7SPJv9Q43vfIkLu16FtwsW0ww5_sASC8',
    appId: '1:115438294651:ios:3641fcb6bd151d994974de',
    messagingSenderId: '115438294651',
    projectId: 'flutter-individual',
    storageBucket: 'flutter-individual.appspot.com',
    iosClientId: '115438294651-l42613c6s9fc4mk2dcq83tfdrhcmkrfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
